version: "3.8"

services:
  trisf-assistant:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: trisf-assistant
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - /mnt/nfs/docker/trisf-assistant/logs:/app/logs

  db:
    image: mysql:8
    container_name: trisf-assistant-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /mnt/nfs/docker/trisf-assistant/mysql:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
