from telegram import Update
from telegram.ext import ContextTypes
import random


COFFEE_LEVELS = [
    "CRITICAL",
    "LOW",
    "WARNING",
    "UNKNOWN",
    "RECOVERING",
    "STABLE",
    "HIGH",
    "OVERFLOW",
]

COFFEE_MESSAGES = [
    "brain service still booting... please standby ya ☕",
    "latency turun setelah 1 sip. system looks healthier now.",
    "deploy mood pending caffeine injection.",
    "coffee queue empty. productivity maybe degraded.",
    "lagi sync sama universe dulu bentar.",
    "runtime masih warming up, jangan expect miracles dulu.",
    "cache otak masih cold start.",
    "lagi reconnect ke motivation server...",
    "coffee detected. performance slightly improved.",
    "seems stable, but jangan diajak meeting dulu.",
    "network ke reality agak packet loss dikit.",
    "CPU usage naik setelah americano masuk.",
    "ops mode activated. let's pretend we're productive.",
    "lagi failover ke kopi kedua.",
    "warning: terlalu banyak ide tapi belum ada kopi.",
    "system recovering... kopi udah masuk setengah cup.",
    "coffee pipeline looks healthy.",
    "masih retry connection ke semangat kerja.",
    "deployment mood delayed by sleepy daemon.",
    "coffee overflow detected. proceed with confidence.",
    "looks stable, but jangan sentuh prod dulu ya.",
    "heartbeat normal. caffeine level acceptable.",
    "lagi autoscaling motivation instance.",
    "coffee not found. fallback ke air putih dulu.",
    "service berjalan tapi jiwa belum fully online.",
    "ops vibe detected. siap pura-pura sibuk.",
    "coffee OK. siap menghadapi ticket random.",
    "status unclear but vibes look promising.",
    "coffee synced. brain latency improved.",
    "kayaknya productive, tapi belum tentu.",
    "lagi warming up mental container.",
    "coffee injected. system confidence increased.",
    "masih partial recovery mode.",
    "monitoring mood... looks unstable but operational.",
    "coffee ready. let's ship something risky today.",
    "lagi debugging kehidupan dikit.",
    "runtime stable-ish. proceed carefully.",
    "coffee accepted. anxiety reduced by 3%.",
    "lagi bootstrap energy environment.",
    "container semangat berhasil start ulang.",
    "morning standup detected. kopi dulu baru bisa align.",
    "currently not in the mood, but trying to be professional about it.",
    "brain bandwidth masih shared hosting.",
    "kopi belum masuk, tapi calendar udah ngegas.",
    "energy lagi lowkey unavailable, please circle back later.",
    "mental state: pending approval from caffeine team.",
    "lagi pretending to be fine in a very enterprise way.",
    "coffee sudah paid, semangat masih waiting for callback.",
    "vibes are operational, logic is still onboarding.",
    "kayaknya bisa kerja, asal tidak ada sudden meeting.",
    "lagi align sama kopi biar deliverables nggak chaos.",
    "caffeine roadmap looks promising, execution masih TBD.",
    "otak lagi loading screen, tapi outfit sudah production-ready.",
    "coffee landed safely. mood mulai comply.",
    "still sleepy, but make it corporate.",
    "kopi tipis-tipis dulu biar nggak terlalu main character.",
    "energy budget approved for one more ticket.",
    "lagi negotiate sama kantuk, so far statusnya complicated.",
    "semangat masih di QA, expected release after second sip.",
    "brain API rate limited. try again after kopi.",
    "coffee masuk, intrusive thoughts keluar dari backlog.",
    "currently in soft-launch mode, jangan push terlalu keras.",
    "meeting bisa, mikir berat jangan dulu.",
    "lagi mencari work-life balance di dasar gelas kopi.",
    "espresso deployed. sleepy service scaled down.",
    "semangat sudah online, tapi masih read-only.",
    "coffee is giving premium subscription energy.",
    "mood lagi unstable, but presentation layer looks fine.",
    "lagi reconnect ke inner peace lewat iced latte.",
    "kopi sudah merge, conflict hidup masih unresolved.",
    "performance naik dikit, confidence naik kebanyakan.",
    "hari ini feels productive-coded, actual output menyusul.",
    "coffee status green, social battery amber.",
    "lagi optimize diri biar kelihatan employable.",
    "caffeine acquired. now entering fake-it-till-prod mode.",
    "otak udah up, tapi observability masih kurang.",
    "kopi pertama buat survive, kopi kedua buat personality.",
    "current vibe: agile, anxious, and adequately caffeinated.",
    "lagi graceful degradation dari ngantuk ke sok sibuk.",
    "coffee confirmed. siap bilang noted with thanks.",
    "badan di kantor, jiwa masih loading di lobby.",
    "energy sudah auto-renew, tapi happiness masih trial version.",
    "kopi membantu, tapi root cause tetap Senin.",
    "mental container restarted, logs look dramatic.",
    "seems fine from dashboard, jangan inspect detailnya.",
    "coffee-driven development sedang berlangsung.",
    "lagi shifting from sleepy to slightly useful.",
    "vibes sudah pass health check, productivity belum.",
    "kopi masuk, kemampuan basa-basi naik 27%.",
    "currently brewing confidence with limited observability.",
]


async def coffee_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    level = random.choice(COFFEE_LEVELS)
    message = random.choice(COFFEE_MESSAGES)

    await update.message.reply_text(
        f"☕ Coffee level: *{level}*\n_{message}_",
        parse_mode="Markdown",
    )
